# Generated by Django 4.1.6 on 2023-09-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="provider",
            field=models.CharField(
                choices=[
                    ("facebook", "facebook"),
                    ("google", "google"),
                    ("email", "email"),
                ],
                default="email",
                max_length=25,
                null=True,
            ),
        ),
    ]
