# Generated by Django 4.1.6 on 2023-10-06 22:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_remove_wishlist_product_wishlistitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together={("product", "wishlist")},
        ),
    ]
