# Generated by Django 4.1.6 on 2023-10-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_cartitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                error_messages={"max_digits": "Retail price must be less than 999.99"},
                help_text="format: required, max_digits=5, decimal_places=2",
                max_digits=7,
                verbose_name="Cart unit price",
            ),
        ),
    ]
